#!/bin/sh
# postinst script for workbox

set -e

LOGDIR='/var/log/workbox'
INSTLOGFILE='/var/log/workbox/install.log'
RMLOGFILE='/var/log/workbox/remove.log'

# create log dir for workbox
[ -d $LOGDIR ] || mkdir $LOGDIR

case "$1" in

  configure)
    # bind ip address
    if ! /bin/grep -q -P '127.0.0.1\tworkbox' /etc/hosts ; then
      /usr/bin/printf "\n# WorkBox service by Chirukhin Alexey\n127.0.0.1\tworkbox\n127.0.0.1\tdev.workbox\n" >> /etc/hosts
    fi

    # disable if site exists
    if [ -f /etc/apache2/sites-enabled/workbox.conf ]
    then
      /bin/date >> $INSTLOGFILE
      /usr/sbin/a2dissite workbox.conf >> $INSTLOGFILE
      printf "\n" >> $INSTLOGFILE
    fi

    # Set up our config for apache
    /usr/bin/printf "<VirtualHost *:80>
    ServerName workbox
    RedirectMatch permanent ^/(.*)$ http://dev.workbox/\$1
</VirtualHost>

<VirtualHost *:80>
    ServerName dev.workbox

    WSGIProcessGroup dev.workbox
    WSGIDaemonProcess dev.workbox user=www-data group=www-data threads=4 python-path=/opt/venvs/workbox/lib/python2.7/site-packages
    WSGIScriptAlias / /opt/venvs/workbox/lib/python2.7/site-packages/workbox/wsgiconfig/app.wsgi

    #Serve static files directly without TurboGears
    Alias /images /opt/venvs/workbox/lib/python2.7/site-packages/workbox/public/images
    Alias /fonts /opt/venvs/workbox/lib/python2.7/site-packages/workbox/public/fonts
    Alias /css /opt/venvs/workbox/lib/python2.7/site-packages/workbox/public/css
    Alias /js /opt/venvs/workbox/lib/python2.7/site-packages/workbox/public/js

    CustomLog \${APACHE_LOG_DIR}/workbox-access_log common
    ErrorLog \${APACHE_LOG_DIR}/workbox-error_log

    # Set access permission
    <Directory \"/opt/venvs/workbox/lib/python2.7/site-packages/workbox\">
        Require all granted
    </Directory>
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet\n" > /etc/apache2/sites-available/workbox.conf

    # enable site
    /bin/date >> $INSTLOGFILE
    /usr/sbin/a2ensite workbox.conf >> $INSTLOGFILE
    printf "\n" >> $INSTLOGFILE
    /etc/init.d/apache2 reload
  ;;

  abort-remove)
    # enable site
    if [ -f /etc/apache2/sites-available/workbox.conf ] && [ ! -f /etc/apache2/sites-enabled/workbox.conf ]
    then
      /bin/date >> $RMLOGFILE
      /usr/sbin/a2ensite workbox.conf >> $RMLOGFILE
      printf "\n" >> $RMLOGFILE
      /etc/init.d/apache2 reload
    fi
  ;;

# ----

  abort-upgrade|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

#DEBHELPER#

exit 0
